spring:
  application:
    name: intergalactic-marketplace

application:
    restclient:
      response-timeout: 2000
    recommendation-service:
      base-path: http://localhost:8081
      url: ${application.recommendation-service.base-path}/recommendation-service/v1/recommendations

greeting:
  greetings:
    bob:
      name: bob
      message: Hello and welcome, ${greeting.greetings.bob.name}
